language: python
services:
- docker
python: 3.6
script:
- make tests
before_deploy:
- pip install poetry
- poetry build
deploy:
  provider: script
  script: poetry publish --username "$PYPI_USER" --password "$PYPI_PASSWORD"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: ZqXR7NNr8OEei8hNA40VXTrUIh6LudoocA4oi+SToVOTybesQnxP9diRjnUPYu6/UtD6B15LbJp7XYuNE6ZjjCebgh+MvBo9Zh7StDNd/MAQOSdFoTO8aja4wvnxZbdS3O38lm+pnyFLIYqLhw6pXa4jbvaarT4cz7WHy7gfERQ18PXRQwIzZhqmrDdw3XNqDxoNyCWrrNjMA4NTYtXG7vLQpuQTzqcHSdjywGH/jK2g5iVCoL3cgD/O2BMI2/l8qhidYgsx8habNWyY1z/OFHJWZn95iNxwo+Jyh2wr2jP6jI0ySBdckA9EClnwE9gal/q/Vtd7TU9VKtyURIu5gxzAtLWUiyVyJJrYtpsuSHFc7pDVIcODnHFzEfjBny/+nGMD4C06qRAjoWmXvb4Isx3Bq8CBcTPKhfXmrVkxV9gQ9q7Aqi8amQUoj+fh+dEQXLCbMTfcIKcHDuTdplvvb/vfb0ymw8DmZ4k4c/B4V/bEgYU2Ta7rdAOkngw+fRmf+5accnPvesVlPCvVixcw/68hi6oPsCbWmvuww4A1JGgeZcf36niv0Fq5TDE7qXcT5yBh/PpqC7cZxEIXcJG++qqTN5FWNeJ3JjdByt+w3P5v+EQLI2gVZP1eMZNrg7RDXmXpEUelB9QamuzrrOLXikX9lIiP75lwv6Nw9mx6iEc=
  - secure: NEHpknOAEGUa6NHFV2CeyB0IjAJpkkWXoEgNulQOmokE3559TY/NZ1lgdih2MdO320LBGWHHlyhA+FSlKYVc874JGlVxKJSK45LCGi7xN2dIrbdU5NQNCp2r2DdktsdRW85aXfRUBdx2Lqrk9FZX6+6ODizf18fWOHBHst6m9KUic0rsDfd4VvWuSbrONBjwbDniwFfYrppy+mtB7QI3VYVavc05ogigY3ZjYnROFM+4AVQV7iK4s/igwbRKBobEphdsV0v6nuMSqNQ3ZSXTKjxFLB6jD0h/g1UHt+41AOXozja5ug7k2DE+BfneXuB6B7mZPWx5YfMgIM9fUHyAS3pmDFXEtbFHD2AV2C1HrZXV9s29pO3yjq38EeRfIrKdNQmRO55x+PH/F5mCsUWCGe6zZD+RZifc3xjEB60I8VkKr6K3zmMaaup9NC4m82hAkK6s+JLdD6Gzv1MGi2H30XhYEBk2unenRZ/UuabCcSoktQyS/w+m+/Tg+0njKV4ZXDBfH8fhQKH9DwWXwMwKMUgOdQzlX6GOb778k6/ewMTjXdqEllbi0zWuTO+jS10fshJdsPb/rJvWVlrff94GUrrhDUlNnFOcSDtjNfsTAitcMMSEf8vnsOIYaLjpuh1rhPUnv6UPYBXk9kWcsJlgt1D/0WANabO0BxZr8oBjkq4=
