language: python
services:
- docker
python: 3.6
script:
- make tests
before_deploy:
- pip install poetry
- poetry build
deploy:
  provider: script
  script: poetry publish --username "$PYPI_USER" --password "$PYPI_PASSWORD"
  skip_cleanup: true
  on:
    tags: true
env:
  global:
  - secure: "pqtOifPhRDK5GPK+32t+sBt4ZIuB8dyzUUrx8H4HMnUyCo+dm9+WJsjAApQcdHpuAwghSE8qzCjKaB2lEdRUNpKxt1Pn1dREbAUpqWNQgCPTWu7JCYGL+akaK4khsPigPBvrUzR1HpPtqBnt2eDM24TFuA/MO4UHZFbXQFoji3r0/Rwb82QO4SVTsPBH5sAd8UF1mIx8KpBO65cYYAv1J89GWvujR+qmlhZEJPKvAC5ZAbH1gnPy4yomXL5KnUdlEMmYjpCdDw8BqTP4xB58azJxcDwTpPVHZQ0ZpEmu4B6dadpzSZCKAqTNberJAFoWcsuOK+6NFyrRCAX/0gsYxbEqWBGE5cDKSRbmiX8Y1LzMpHzdAFe6y5OrdanHmZYq3ZlQibLTkYRd0Z1Wlhvfe1SNdQvaBpG1D3My7Yh7ee54FNMuxK5HuRiMlLdlv1PsFQ4IM/XOjf1dwAl2CdOCs7xiehl/0hL2AbBQivMKZqKu6B4SY5joy6+5lk3ISujo5iPcXaNLxNCfWqm5i6V0c+89jubPnrOBvuBRIWbFVJpngnm5GsKyt6E0nQimZzEs9Ybh/hT+eCWH7PP+RkFXWQSneF3wZxzzKBKjbm69GI6Fla/ta2XuB1gflhRpM9doku7lfCGADOohmGUHDAoP0P8Oa+oZW7YFwGOCXtppLII="
  - secure: "eNV+7xnQUqnFf0cbzbPlX/fribTZmJ3WrEzXf4ibJFXxYCkV7yvfwx6cd+O40r6UeGOjBjzPtQ/X1Po6UflwMUjGYc3lu8n8VT3O/yMasdz6xmLmQyCux1KcqOnsZvY+NnlYdEsSUeCYplCqf8hlg5rgMHNQmh4MVpc817TyAZq+0IWXvlzrmpDaDrAr3meyHglYYDW0y+P9grPEo/nWjAw9Ol+GB/2HNMEzj8bWi+ZZCCRerWmyxviD7bwQTXDk4oNMdX3rAz2E/I65Lgk2ena4TM/hkGY5Tel5ppPxvITZDBu4xy52rUTuWfNSFG8n4kshpv0ZgMSEIi3ckdqg1+LLnXcBfg9XL1wgKvYU4GLIMJw+mDrOX3uaOm0UTsFQVHou/Bi2TC+tLaiT9ZHTD9fP72n0qeenwQT04yLEOKdWKRy0G39oVMNQzRwu8Te1nv3ofGYhttqHlwCNeWfeqaTAQO33sm8VQZSPH3WMeqRBrCscTTEBroYAmHsLUEw49UYZjEEU7d8TLaa/9iXBSOVUlclPwAmS1+S4GwSl7SsmtwXkAE1BnlPhzi8194SAkHxu8QnZqMUiIaSOyMnlb6X9yVgtgVPt/fjA9HytIDW7gC4N21k/fdUfs00f8iakkkIEhhHx/wiZb76ahSOsRWTCjRbLjVwQy6wbWTCwADw="

